# Generated by Django 6.0.4 on 2026-04-26 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriptions', models.TextField(max_length=255, unique=True)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('qty', models.IntegerField(default=0)),
                ('costprice', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('sellprice', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('saleprice', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('productpicture', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('alertstocks', models.IntegerField(default=0)),
                ('criticalstocks', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category')),
            ],
        ),
    ]
